# Generated by Django 4.2.4 on 2023-09-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'КЛИНИЦИСТ'), (2, 'Админ программ'), (3, 'НАСТРОЙКА ПАКЕТОВ'), (4, 'Настройка услуг'), (5, 'АССИСТАНС'), (6, 'Страховой контракт'), (7, 'Справочник'), (8, 'Админ контрактов'), (11, 'Medassitance'), (12, 'Прайскурация/расчеты'), (13, 'КЛИНИЦИСТ ОЦЕНКА'), (14, 'Настройка мкб-10'), (15, 'Настройка мкб-10 ЛПУ'), (16, 'Отчет'), (17, 'Админ страховой компании'), (18, 'Админ больницы'), (19, 'Админ промедицина'), (20, 'Админ промедицина больницы')], default=1),
        ),
    ]
