# Generated by Django 4.2.4 on 2023-08-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('referral_management', '0001_initial'),
        ('contract_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEPSDMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=320)),
                ('icd', models.CharField(max_length=320)),
                ('full_name', models.CharField(max_length=320)),
                ('iin', models.CharField(max_length=320)),
                ('contract_customer', models.CharField(max_length=320)),
                ('referral', models.CharField(blank=True, max_length=320, null=True)),
                ('hospital', models.CharField(blank=True, max_length=320, null=True)),
                ('consumption', models.CharField(blank=True, max_length=320, null=True)),
                ('screen', models.TextField(blank=True, null=True)),
                ('performing_doctor', models.CharField(blank=True, max_length=180, null=True)),
                ('doctor_signature', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('type_appeal', models.IntegerField(choices=[(1, 'ОМС'), (2, 'ДМС'), (3, 'Платно')])),
                ('place', models.IntegerField(choices=[(1, 'На дому'), (2, 'ПМСП'), (3, 'Амбулаторно'), (4, 'Стационарно')])),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('screen', models.TextField(blank=True, null=True)),
                ('performing_doctor', models.CharField(blank=True, max_length=180, null=True)),
                ('doctor_signature', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('type_appeal', models.IntegerField(choices=[(1, 'ОМС'), (2, 'ДМС'), (3, 'Платно')])),
                ('place', models.IntegerField(choices=[(1, 'На дому'), (2, 'ПМСП'), (3, 'Амбулаторно'), (4, 'Стационарно')])),
                ('contract_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.contractcustomer')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.hospital')),
                ('icd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.icd')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referral_management.referral')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.service')),
            ],
        ),
    ]
