# Generated by Django 3.2.4 on 2023-08-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_management', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_code', models.CharField(max_length=10, verbose_name='Doctor Code')),
                ('date_time', models.DateTimeField(verbose_name='Appointment Date and Time')),
                ('status', models.CharField(choices=[('Planned', 'Запланирован'), ('Completed', 'Выполнен'), ('Canceled', 'Отменен')], default='Planned', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start_date', models.DateTimeField(blank=True, null=True)),
                ('plan_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Запланирован'), ('Completed', 'Выполнен')], default='Planned', max_length=15)),
                ('contract_customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract_management.contractcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(verbose_name='Conclusion')),
                ('recommendations', models.TextField(verbose_name='Recommendations')),
                ('examination_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.examinationappointment')),
                ('icd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.icd')),
            ],
        ),
        migrations.AddField(
            model_name='examinationappointment',
            name='professional_examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.professionalexamination'),
        ),
        migrations.AddField(
            model_name='examinationappointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.service'),
        ),
    ]
