# Generated by Django 3.2.4 on 2023-08-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promedicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
            ],
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='conclusion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promedicine.conclusion'),
        ),
    ]
