# Generated by Django 3.2.4 on 2023-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promedicine', '0004_hazardreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreference',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Название вредности'),
        ),
    ]
