# Generated by Django 4.2.4 on 2023-08-14 04:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=180, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.insurance')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.insurer')),
            ],
        ),
        migrations.CreateModel(
            name='ContractHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Отправить'), (2, 'Отправлен'), (3, 'Заявка принята'), (4, 'Заявка переотправлена')], default=1)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.contract')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('status', models.IntegerField(choices=[(1, 'Ожидание'), (2, 'Заявка страховой компании'), (3, 'Подтверждение провайдера'), (4, 'Контракт')], default=1)),
                ('contract_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.contracthospital')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='directory.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('limit', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('limit_type', models.IntegerField(choices=[(1, 'Полное покрытие'), (2, 'Лимит на стоимость услуг'), (3, 'Лимит на количество услуг')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('is_favorite', models.BooleanField(default=False)),
                ('limit_percent', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('premium_percent', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.contract')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_at_home', models.FloatField(blank=True, null=True)),
                ('state_primary_health_care', models.FloatField(blank=True, null=True)),
                ('state_clinical_diagnostic', models.FloatField(blank=True, null=True)),
                ('state_hospital', models.FloatField(blank=True, null=True)),
                ('vhi_at_home_coefficient', models.FloatField(blank=True, null=True)),
                ('vhi_primary_health_care_coefficient', models.FloatField(blank=True, null=True)),
                ('vhi_clinical_diagnostic_coefficient', models.FloatField(blank=True, null=True)),
                ('vhi_hospital_coefficient', models.FloatField(blank=True, null=True)),
                ('vhi_price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('pay_at_home_coefficient', models.FloatField(blank=True, null=True)),
                ('pay_primary_health_care_coefficient', models.FloatField(blank=True, null=True)),
                ('pay_clinical_diagnostic_coefficient', models.FloatField(blank=True, null=True)),
                ('pay_hospital_coefficient', models.FloatField(blank=True, null=True)),
                ('pay_base_price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('limit', models.FloatField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='directory.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='package',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.program'),
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='directory.service'),
        ),
        migrations.CreateModel(
            name='HospitalPackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_at_home', models.FloatField(blank=True, null=True)),
                ('state_primary_health_care', models.FloatField(blank=True, null=True)),
                ('state_clinical_diagnostic', models.FloatField(blank=True, null=True)),
                ('state_hospital', models.FloatField(blank=True, null=True)),
                ('vhi_at_home_coefficient', models.FloatField(blank=True, null=True)),
                ('vhi_primary_health_care_coefficient', models.FloatField(blank=True, null=True)),
                ('vhi_clinical_diagnostic_coefficient', models.FloatField(blank=True, null=True)),
                ('vhi_hospital_coefficient', models.FloatField(blank=True, null=True)),
                ('vhi_price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('pay_at_home_coefficient', models.FloatField(blank=True, null=True)),
                ('pay_primary_health_care_coefficient', models.FloatField(blank=True, null=True)),
                ('pay_clinical_diagnostic_coefficient', models.FloatField(blank=True, null=True)),
                ('pay_hospital_coefficient', models.FloatField(blank=True, null=True)),
                ('pay_base_price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('hospital_at_home_coefficient', models.FloatField(blank=True, null=True)),
                ('hospital_primary_health_care_coefficient', models.FloatField(blank=True, null=True)),
                ('hospital_clinical_diagnostic_coefficient', models.FloatField(blank=True, null=True)),
                ('hospital_hospital_coefficient', models.FloatField(blank=True, null=True)),
                ('hospital_price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('insurance_at_home_coefficient', models.FloatField(blank=True, null=True)),
                ('insurance_primary_health_care_coefficient', models.FloatField(blank=True, null=True)),
                ('insurance_clinical_diagnostic_coefficient', models.FloatField(blank=True, null=True)),
                ('insurance_hospital_coefficient', models.FloatField(blank=True, null=True)),
                ('insurance_base_price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('hospital_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.hospitalpackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='directory.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contracthospital',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.program'),
        ),
        migrations.CreateModel(
            name='ContractCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, unique=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type_holder', models.IntegerField(choices=[(1, 'Основной держатель'), (2, 'Родитель'), (3, 'Супруга'), (4, 'Дети')], default=1)),
                ('base_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract_management.contractcustomer')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.program')),
            ],
        ),
    ]
