# Generated by Django 3.2 on 2023-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='insurance_type',
            field=models.IntegerField(choices=[(1, 'Добровольное медицинское страхование'), (2, 'профессиональное медицинское страхование')], default=1),
        ),
    ]
