# Generated by Django 4.0.3 on 2022-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=180)),
                ('last_name', models.CharField(max_length=180)),
                ('surname', models.CharField(max_length=180)),
                ('national', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=180)),
                ('place_work', models.CharField(max_length=180)),
                ('telephone_number', models.CharField(max_length=180)),
                ('profession', models.CharField(max_length=180)),
                ('iin', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
