# Generated by Django 4.2.4 on 2023-08-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('program_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.insurer'),
        ),
    ]
