# Generated by Django 4.2.4 on 2023-08-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0002_program_insurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.IntegerField(choices=[(1, 'ДМС'), (2, 'ОМО'), (3, 'ОПМО')], default=1),
        ),
    ]
