# Generated by Django 4.2.4 on 2023-08-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_code', models.CharField(max_length=10, verbose_name='Doctor Code')),
                ('date_time', models.DateTimeField(verbose_name='Appointment Date and Time')),
                ('status', models.CharField(choices=[('Planned', 'Запланирован'), ('Completed', 'Выполнен'), ('Canceled', 'Отменен')], default='Planned', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Factory title')),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Hazard title')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Profession title')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.hazard')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.profession')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateTimeField(verbose_name='Examination Date')),
                ('status', models.CharField(choices=[('Planned', 'Запланирован'), ('Completed', 'Выполнен')], default='Planned', max_length=15)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.factory')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.profession')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkb_10_code', models.CharField(max_length=10, verbose_name='MKB-10 Code')),
                ('conclusion', models.TextField(verbose_name='Conclusion')),
                ('recommendations', models.TextField(verbose_name='Recommendations')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.examinationappointment')),
            ],
        ),
        migrations.AddField(
            model_name='examinationappointment',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.professionalexamination'),
        ),
        migrations.AddField(
            model_name='examinationappointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.service'),
        ),
    ]
