# Generated by Django 4.2.4 on 2023-08-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('promedicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardServiсe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedicine.hazard')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.service')),
            ],
        ),
    ]
