# Generated by Django 4.2.4 on 2023-08-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('promedicine', '0002_hazardserviсe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexamination',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='professionalexamination',
            name='examination_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Examination Date'),
        ),
    ]
