# Generated by Django 4.2.4 on 2023-08-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('contract_management', '0001_initial'),
        ('promedicine', '0004_auto_20230822_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationappointment',
            old_name='examination',
            new_name='professional_examination',
        ),
        migrations.RenameField(
            model_name='examinationresult',
            old_name='appointment',
            new_name='examination_appointment',
        ),
        migrations.RemoveField(
            model_name='examinationresult',
            name='mkb_10_code',
        ),
        migrations.RemoveField(
            model_name='professionalexamination',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='professionalexamination',
            name='examination_date',
        ),
        migrations.RemoveField(
            model_name='professionalexamination',
            name='insurer',
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='icd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.icd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionalexamination',
            name='contract_customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract_management.contractcustomer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionalexamination',
            name='plan_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalexamination',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
