# Generated by Django 3.2.4 on 2023-08-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0001_initial'),
        ('directory', '0001_initial'),
        ('promedicine', '0005_rename_examination_examinationappointment_professional_examination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationresult',
            name='icd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.icd'),
        ),
        migrations.AlterField(
            model_name='professionalexamination',
            name='contract_customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract_management.contractcustomer'),
        ),
    ]
