# Generated by Django 3.2.4 on 2023-08-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promedicine', '0005_auto_20230822_1234'),
        ('promedicine', '0006_auto_20230824_1259'),
    ]

    operations = [
    ]
