# Generated by Django 3.2 on 2023-08-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('package_service_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.insurer'),
        ),
    ]
